#!/bin/bash
sxhkd -c ~/.config/sxhkd/sxhkdrc &
picom &
syncthing &
$HOME/.config/polybar/launch.sh &
xscreensaver &
feh --bg-fill ~/walp/12270-dark-void-wallpaper-voidlinux.png

bspc monitor -d 1 2 3 4 5 6 7 8 9 10
bspc rule -a firefox desktop=^2

bspc config border_radius 8
bspc config border_width 0
bspc config focus_follows_pointer true
bspc config pointer_modifier super
# bspc config 
# bspc config 
# bspc config 
# bspc config 
# bspc config 
# bspc config 
# bspc config 
# bspc config 
# bspc config 
# bspc config 
# bspc config 
# bspc config 
# bspc config 
