#!/bin/bash

while true
do
    #echo ""
    out=$(cat ~/.config/waybar/store/dynamic_out.txt)
    #echo "$out"  | jq --unbuffered --compact-output
    cat ~/.config/waybar/store/dynamic_out.txt
    sleep 0.5
done
